config/routes.rb
Rails.application.routes.draw do
  get 'delboysession/new'
  post 'delboysession/create'
  delete 'delboysession/destroy'
  get '/delboyconfdel' => 'misc#delboyconfdel', :as => 'conf_del_delboy'
  post '/cartminuss/:id' => 'cart#cartminus', :as => 'crtminus'
  # get 'delaerdelivery/index'
  # get 'delaerdelivery/:id', to: 'delaerdelivery#show'
  get '/homepage' => 'homepage#index', :as => 'home_page'
  # get 'dealersession/new'
  # get 'dealersession/create'
  # get 'dealersession/destroy'
  # get 'customersession/new'
  # post 'customersession/create'
  # delete 'customersession/destroy'
  	resources :dealersession, only: [:new, :create, :destroy]
  	resources :customersession, only: [:new, :create, :destroy]
	resources :customers
	resources :customerpersonalinfos, only: [:new, :create, :edit, :update, :destroy, :show]
	resources :dealers
	resources :dealerpersonalinfos
	resources :products
	resources :cart
	resources :checkout, only: [:index, :create]
	delete '/cancelorder/:conf' => 'checkout#destroy', :as => 'cancel_order'
	resources :delaerdelivery
	get '/confdel' => 'delaerdelivery#conf', :as => 'conf_del'
	get '/search' => 'pages#search', :as => 'search_page'
	get '/pendingorders' => 'misc#pendingorder_user', :as => 'pending_order_user'
	get '/pendingordersbc/:configkey' => 'misc#pendingorder_userbc', :as => 'pending_order_userbc'
	get '/allorders' => 'misc#allorder_user', :as => 'all_order_user'
	get '/delboypendingorders' => 'misc#delboypendings', :as => 'delboy_pendings'
	get '/delboypeningorders/:id' => 'misc#delboypendingsbc', :as => 'delboy_pendingsbc'
	get '/home' => 'homepage#indexws', :as => 'homepagews'
	get '/editaddressform' => 'misc#editaddress_form', :as => 'editadd'
	post '/updateaddress' => 'misc#editaddress', :as => 'editaddpost' 
	post '/checkaval' => 'homepage#checkaval', :as => 'check_servicable'

	root to: "homepage#index"

	get "/login" => "customersession#new", as: "login"
	delete "/logout" => "customersession#destroy", as: "logout"
	get "/dealerlogin" => "dealersession#new", as: "dealerlogin"
	delete "/dealerlogout" => "dealersession#destroy", as: "dealerlogout"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/allorder.rb
class Allorder < ApplicationRecord
  belongs_to :product
  belongs_to :customer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :customer
  belongs_to :product
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_secure_password

	has_one :customerpersonalinfo, dependent: :destroy
	has_many :cart, dependent: :destroy
	has_many :checkout, dependent: :destroy
	validates :email, presence: true
	validates :password, presence: true
end

app/models/customerpersonalinfo.rb
class Customerpersonalinfo < ApplicationRecord
  belongs_to :customer
	validates :name, presence: true
	validates :phone, presence: true
	validates :address, presence: true
end

app/models/dealer.rb
class Dealer < ApplicationRecord
	has_secure_password

	has_one :dealerpersonalinfo
	has_many :products
	validates :email, presence: true
	validates :password, presence: true
	has_many :ptd, through: :products, source: :pendingorder 
end

app/models/dealerpersonalinfo.rb
class Dealerpersonalinfo < ApplicationRecord
  belongs_to :dealer
	validates :shopname, presence: true
	validates :phone, presence: true
end

app/models/delboy.rb
class Delboy < ApplicationRecord
	has_secure_password

	
end

app/models/pendingorder.rb
class Pendingorder < ApplicationRecord
  belongs_to :product
  belongs_to :customer
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :dealer
  has_many :cart, dependent: :destroy
  has_many :pendingorder, dependent: :destroy

  mount_uploader :image, PhotoUploader
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
	skip_before_action :ensure_login_dealer
	skip_before_action :ensure_login_delboy
	def index
		@price = 0
		@cart = current_user().cart
	end


	def update
		@product = Product.find_by(id: params[:id])
		@carttosave = Cart.new
		@carttosave.product_id = @product.id
		if current_user.cart.find_by(product_id: @carttosave.product_id) != nil
			current_user.cart.find_by(product_id: @carttosave.product_id).update!(:quantity => current_user.cart.find_by(product_id: @carttosave.product_id).quantity+1)
		else
			@carttosave.customer_id = current_user.id
			# @carttosave.product_id = @product.id
			@carttosave.quantity = 1
			@carttosave.save
		end
		respond_to do |format|
			format.js
		end
	end

	def cartminus
		@productquan
		@product = Product.find(params[:id])
		@carttodel = Cart.find_by(product_id: @product.id)
		if current_user.cart.find_by(product_id: @carttodel.product_id).quantity == 1
			@carttodel.destroy
			@productquan = 0
		elsif current_user.cart.find_by(product_id: @carttodel.product_id).quantity == nil
			# do nothing
		else
			current_user.cart.find_by(product_id: @carttodel.product_id).update!(:quantity => current_user.cart.find_by(product_id: @carttodel.product_id).quantity-1)
			@productquan = current_user.cart.find_by(product_id: params[:id]).quantity
		end
		respond_to do |format|
			format.js
		end
	end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
	skip_before_action :ensure_login_user
	skip_before_action :ensure_login_dealer
  skip_before_action :ensure_login_delboy
  def index
  	if params[:search].blank?
  		redirect_to homepagews_path
  	else
  		@parameter = params[:search].downcase
  		# @allproducts = Product.all.where("lower(tags) LIKE :search", search: "%#{@parameter}%")
      if logged_in?  
        @allproducts = Dealerpersonalinfo.find_by(pincode: current_user.customerpersonalinfo.pincode).dealer.products.where("lower(tags) LIKE :search", search: "%#{@parameter}%")
      else 
        @allproducts = Product.all.where("lower(tags) LIKE :search", search: "%#{@parameter}%")
      end
    end
  end

  def indexws
  end

  def checkaval
    @result = false
    @pincode = params[:pincode]
    if Dealerpersonalinfo.find_by(pincode: @pincode)
      @result = true
    end
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/misc_controller.rb
class MiscController < ApplicationController
	skip_before_action :ensure_login_dealer, only: [:pendingorder_user, :allorder_user, :delboypendings, :delboypendingsbc, :delboyconfdel, :pendingorder_userbc, :editaddress, :editaddress_form]
	skip_before_action :ensure_login_delboy, only: [:pendingorder_user, :allorder_user, :pendingorder_userbc, :editaddress, :editaddress_form]

	skip_before_action :ensure_login_user, only: [:delboypendings, :delboypendingsbc, :delboyconfdel]
	
	def pendingorder_user
		@allpo = Pendingorder.where(customer_id: current_user.id).group(:confkey).count
	end

	def pendingorder_userbc
		@key = params[:configkey]
		@pendingsbc = Pendingorder.where(customer_id: current_user.id).where(confkey: @key)
	end
	
	def allorder_user
		@allo = Allorder.where(customer_id: current_user.id).group(:created_at).count
	end

	def delboypendings
		@allptd = Pendingorder.group(:customer_id).count
	end

	def delboypendingsbc
		@customer = params[:id]
		@price = 0
		@allptdbc = Pendingorder.where(customer_id: @customer)
	end

	def delboyconfdel
		@conf = params[:conf_key]
		@todesandadd = Pendingorder.where(confkey: @conf)
		@todesandadd.each do |toaddanddes|
  			@toaddo = Allorder.new
  			@toaddo.quantity = toaddanddes.quantity
  			@toaddo.product_id = toaddanddes.product_id
  			@toaddo.customer_id = toaddanddes.customer_id
  			@toaddo.save
  			# @toaddanddes.destroy
  		end
  		@todesandadd.destroy_all
  		flash['Notification'] = 'Delivered'
  		redirect_to delboy_pendings_path
	end

	def editaddress_form 

	end

	def editaddress 
		current_user.customerpersonalinfo.update!(:name => params[:name])
		current_user.customerpersonalinfo.update!(:phone => params[:phone])
		current_user.customerpersonalinfo.update!(:address => params[:address])
		flash['Notification'] = 'Personal Info updated'
		redirect_to home_page_path
	end

	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dealers_helper.rb
module DealersHelper
end

app/helpers/dealersession_helper.rb
module DealersessionHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/misc_helper.rb
module MiscHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/homepage/checkaval.js.erb
$(".servicableornot").hide('fast', 'swing');
<% if @result %>
	$(".servicable").show('fast', 'swing');
<% else %>
	$(".notservicable").show('fast', 'swing');
<% end %>

app/views/homepage/index.html.erb
<div class="container" style="margin-top: 130px;">
<% if @allproducts.count > 0 %>
	<% @allproducts.each do |product| %>
		<div class="product-box">
				<div class="row">	
					<div class="col-5 col-sm-3 col-md-2 col-lg-2 col-xl-2">
						<%= image_tag(product.image.profile_size.url, size: 120) %>
					</div>
					<div class="product-box-info col-7 col-sm-9 col-md-10 col-lg-10 col-xl-10">
						<b><%= product.name %></b>
						<br/>
						<i><%= product.description %></i>
						<br>
						<div class="price">
							<i class="fa fa-rupee-sign" style="font-weight: lighter;"></i>
							<%= product.price %>
						</div>
					</div>
				</div>
			<div class="row" style="position: absolute; right: 3rem; top: 85%; width: 3.4rem; height: 1.2rem;">
				
					<div class="no-padding col-3 col-sm-3 col-md-3">
						<span>	
							<%= link_to crtminus_path(product.id), method: :post, remote: true, id: "subtfromcartbtn-#{product.id}" do %>
								<i class="fa fa-minus-square" style="font-size: 1.2rem;"></i>
							<% end %>
						</span>
					</div>
					<div style="text-align: center;" class="col-6 col-sm-6 col-md-6 no-padding">
						<span id="quantityhomepage-<%= product.id %>" >
							<% if logged_in? %>
								<% if Cart.where(customer_id: current_user.id).exists?(:product_id => product.id) %>
									<%= Cart.where(customer_id: current_user.id).find_by(product_id: product.id).quantity %>
								<% else %>
									0
								<% end %>
							<% else %>
								0
							<% end %>
						</span>
					</div>
					<div class="col-3 col-sm-3 col-md-3 no-padding">
						<%= link_to  cart_path(product.id), method: :patch, :remote => true, :id => "addtocartbtn-#{product.id}" do %>
							<i class="fa fa-plus-square" style="font-size: 1.2rem;"></i>
						<% end %>
					</div>
				
					
			</div>
			
		</div>
		<hr>
		<script type="text/javascript">
			$("#addtocartbtn-<%= product.id %>").click(function(){
				let newquan = parseInt($('#quantityhomepage-<%= product.id %>').html()) + 1;
				$('#quantityhomepage-<%= product.id %>').html(newquan);
			});
			$("#subtfromcartbtn-<%= product.id %>").click(function(){
				let newquan = 0;
				if(parseInt($('#quantityhomepage-<%= product.id %>').html())!=0) {
					newquan = parseInt($('#quantityhomepage-<%= product.id %>').html()) - 1;
				}
				$('#quantityhomepage-<%= product.id %>').html(newquan);
			});
		</script>
	<% end %>
<% else %>
	<div style="width: 100%; margin: 7rem auto 0; text-align: center;">
		<%= image_tag('nothing-found-logo.png', size: 150 ) %>
		<h5>Oops! Looks like we don't have what you are looking for....</h5>
		<h7>We are constantly adding new products...</h7>
	</div>
<% end %>
</div>

app/views/homepage/indexws.html.erb
<div class="container" style="margin-top: 130px;">
<% if session[:customer_id] %>	
	<div class="row homepage-top-block" style="min-height: 100px;">
		<div class="col-7 col-sm-7 col-md-7">
			<b>Delivering to: </b><br>
			<%= current_user.customerpersonalinfo.address %><br>
		</div>
		<%= link_to editadd_path, class: 'col-2 col-sm-2 col-md-2' do %>
			<div class="btn btn-outline-primary btn-sm" style="margin-top: 1.4rem;">
				<span class="fa fa-pen"></span>
			</div>
		<% end %>
		<div class="col-3 col-sm-3 col-md-3" style="overflow: hidden; padding: 0;">
			<%= image_tag('delivery-bike-logo.png', size: 100) %>
		</div>
	</div>
<% else %>
	<div class="servicableornot">
		We can't check if we are servicable in your region. Please log in to get products according to your location.<br><br>
		<%= form_for(:homepage, url: check_servicable_path, :remote => true, class: 'availability-check-form form-inline my-2 my-lg-0', style: 'text-align: center;') do |form| %>
				<div class="float-left" style="width: 75%;">
		      		<%= phone_field_tag :pincode, params[:pincode], placeholder: "Enter your area pincode", class: "form-control mr-sm-2" %>
		      	</div>
		      	<div class="input-group-btn float-left" style="margin-bottom: 1rem; width: 25%;">  
		        	<button onClick="checking();" type="submit" class="btn btn-info check-btn">
		        		Check
		    		</button>  
	     	  	</div>
  		<% end %>
	</div>
  	<div class="servicable">
  		We are available in your region. 😍 Log in and place your first order.
  	</div>
  	<div class="notservicable">
  		We are currently not available in your region. 😔 We are expanding fast and hoping to reach maximum people as soon as possible.
  	</div>
<% end %>
<br>
<div id="carouselExampleInterval" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active" data-interval="3000">
    	<a href="/homepage?search=bajaj almond drops" class="element-inline"></a>
      <%= image_tag('carousel/caro1.jpg', class: 'carousel-imgs') %>
    </div>
    <div class="carousel-item" data-interval="3000">
    	<a href="/homepage?search=tata sampann" class="element-inline"></a>
      <%= image_tag('carousel/caro2.jpg', class: 'carousel-imgs') %>
    </div>
    <div class="carousel-item" data-interval="3000">
    	<a href="/homepage?search=quick-food" class="element-inline"></a>
      <%= image_tag('carousel/caro3.jpg', class: 'carousel-imgs') %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


<div class="space-1"></div>
<div class="space-1"></div>
<h4> Snacks </h4>
<hr>
	<div class="row">
		<div class="col-6 col-sm-6 col-md-6 no-padding">	
			<a href="/homepage?search=biscuit" class="element-inline">
				<%= image_tag('snacks/biscuits.jpg', class: 'cat-icons') %>
			</a>
		</div>
		<div class="col-6 col-sm-6 col-md-6 no-padding">	
			<a href="/homepage?search=breakfast" class="element-inline">
				<%= image_tag('snacks/breakfast.jpg', class: 'cat-icons') %>
			</a>
		</div>
		<div class="col-6 col-sm-6 col-md-6 no-padding">	
			<a href="/homepage?search=noodle" class="element-inline">
				<%= image_tag('snacks/noodles.jpg', class: 'cat-icons') %>
			</a>
		</div>
		<div class="col-6 col-sm-6 col-md-6 no-padding">	
			<a href="/homepage?search=nut" class="element-inline">
				<%= image_tag('snacks/nuts.jpg', class: 'cat-icons') %>
			</a>
		</div>
	</div>
<hr>
<h4> Cooking Stuffs </h4>
<hr>
<div class="row">	
	<div class="col-6 col-sm-6 col-md-6 no-padding">
		<a href="/homepage?search=flour" class="element-inline">
			<%= image_tag('Cooking_stuffs/flour.jpg', class: 'cat-icons') %>
		</a>
	</div>
	<div class="col-6 col-sm-6 col-md-6 no-padding">
		<a href="/homepage?search=pulse" class="element-inline">
			<%= image_tag('Cooking_stuffs/pulses.jpg', class: 'cat-icons') %>
		</a>
	</div>
	<div class="col-6 col-sm-6 col-md-6 no-padding">
		<a href="/homepage?search=rice" class="element-inline">
			<%= image_tag('Cooking_stuffs/rice.jpg', class: 'cat-icons') %>
		</a>
	</div>
	<div class="col-6 col-sm-6 col-md-6 no-padding">
		<a href="/homepage?search=spice" class="element-inline">
			<%= image_tag('Cooking_stuffs/spices.jpg', class: 'cat-icons') %>
		</a>
	</div>
</div>
<hr>
<h4> Personal Care </h4>
<hr>
<div class="row">	
	<div class="col-6 col-sm-6 col-md-6 no-padding">	
		<a href="/homepage?search=detergent">
			<%= image_tag('personal_care/detergents.jpg', class: 'cat-icons') %>
		</a>
	</div>
	<div class="col-6 col-sm-6 col-md-6 no-padding">	
		<a href="/homepage?search=health drink">
			<%= image_tag('personal_care/health_drinks.jpg', class: 'cat-icons') %>
		</a>
	</div>
	<div class="col-6 col-sm-6 col-md-6 no-padding">	
		<a href="/homepage?search=oral">
			<%= image_tag('personal_care/oral_care.jpg', class: 'cat-icons') %>
		</a>
	</div>
	<div class="col-6 col-sm-6 col-md-6 no-padding">	
		<a href="/homepage?search=sugar salt">
			<%= image_tag('personal_care/salt_and_sugar.jpg', class: 'cat-icons') %>
		</a>
	</div>
</div>
</div>
 <footer>
 <div class="row">
  <div class = "col-6 col-sm-6 col-md-6">
    <b><u>Contact Us</u></b><br>
    <div class="product-box-info">  
       complaint@ekiraana.store
    </div>
      9057686840
    </div>
    <div class = "col-6 col-sm-6 col-md-6">
      <b><u>Address</u></b><br>
      In front of GM Academy School, <br>
      Salempur, Uttar Pradesh - 274509
    </div>
  </div>
</footer>

<script>
	$(".servicable").hide();
	$(".notservicable").hide();
	function checking() {
		$(".check-btn").html('Check<span class="fa fa-sync fa-spin"></span>');
		// $(".check-btn").append('<span class="fa fa-sync fa-spin"></span>');
	}
</script>