config/routes.rb
Rails.application.routes.draw do
  get 'delboysession/new'
  post 'delboysession/create'
  delete 'delboysession/destroy'
  get '/delboyconfdel' => 'misc#delboyconfdel', :as => 'conf_del_delboy'
  post '/cartminuss/:id' => 'cart#cartminus', :as => 'crtminus'
  # get 'delaerdelivery/index'
  # get 'delaerdelivery/:id', to: 'delaerdelivery#show'
  get '/homepage' => 'homepage#index', :as => 'home_page'
  # get 'dealersession/new'
  # get 'dealersession/create'
  # get 'dealersession/destroy'
  # get 'customersession/new'
  # post 'customersession/create'
  # delete 'customersession/destroy'
  	resources :dealersession, only: [:new, :create, :destroy]
  	resources :customersession, only: [:new, :create, :destroy]
	resources :customers
	resources :customerpersonalinfos, only: [:new, :create, :edit, :update, :destroy, :show]
	resources :dealers
	resources :dealerpersonalinfos
	resources :products
	resources :cart
	resources :checkout, only: [:index, :create]
	delete '/cancelorder/:conf' => 'checkout#destroy', :as => 'cancel_order'
	resources :delaerdelivery
	get '/confdel' => 'delaerdelivery#conf', :as => 'conf_del'
	get '/search' => 'pages#search', :as => 'search_page'
	get '/pendingorders' => 'misc#pendingorder_user', :as => 'pending_order_user'
	get '/pendingordersbc/:configkey' => 'misc#pendingorder_userbc', :as => 'pending_order_userbc'
	get '/allorders' => 'misc#allorder_user', :as => 'all_order_user'
	get '/delboypendingorders' => 'misc#delboypendings', :as => 'delboy_pendings'
	get '/delboypeningorders/:id' => 'misc#delboypendingsbc', :as => 'delboy_pendingsbc'
	get '/home' => 'homepage#indexws', :as => 'homepagews'
	get '/editaddressform' => 'misc#editaddress_form', :as => 'editadd'
	post '/updateaddress' => 'misc#editaddress', :as => 'editaddpost' 
	post '/checkaval' => 'homepage#checkaval', :as => 'check_servicable'

	root to: "homepage#index"

	get "/login" => "customersession#new", as: "login"
	delete "/logout" => "customersession#destroy", as: "logout"
	get "/dealerlogin" => "dealersession#new", as: "dealerlogin"
	delete "/dealerlogout" => "dealersession#destroy", as: "dealerlogout"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/dealer.rb
class Dealer < ApplicationRecord
	has_secure_password

	has_one :dealerpersonalinfo
	has_many :products
	validates :email, presence: true
	validates :password, presence: true
	has_many :ptd, through: :products, source: :pendingorder 
end

app/controllers/dealers_controller.rb
class DealersController < ApplicationController
  before_action :set_dealer, only: [:show, :edit, :update, :destroy]
  skip_before_action :ensure_login_user
  skip_before_action :ensure_login_delboy
  skip_before_action :ensure_login_dealer, only: [:new, :create]

  # GET /dealers
  # GET /dealers.json
  def index
    @dealers = Dealer.all
  end

  # GET /dealers/1
  # GET /dealers/1.json
  def show
  end

  # GET /dealers/new
  def new
    @dealer = Dealer.new
  end

  # GET /dealers/1/edit
  def edit
  end

  # POST /dealers
  # POST /dealers.json
  def create
    @dealer = Dealer.new(dealer_params)

    # respond_to do |format|
    if Dealer.find_by(email: params[:dealer][:email])  != nil
      redirect_to new_dealer_path, alert: "Someone with this username already exist, Try another"
      return
    end
      
      if @dealer.save
      #   format.html { redirect_to @dealer, notice: 'Dealer was successfully created.' }
      #   format.json { render :show, status: :created, location: @dealer }
      # else
      #   format.html { render :new }
      #   format.json { render json: @dealer.errors, status: :unprocessable_entity }
      # end
        current_dealer = Dealer.find_by(email: params[:dealer][:email])
        password = params[:dealer][:password]
      end

    if current_dealer && current_dealer.authenticate(password)
      session[:dealer_id] = current_dealer.id
      redirect_to new_dealerpersonalinfo_path, notice: "Logged In as Dealer"
    else
      redirect_to dealerlogin_path, alert: "Wrong Credentials"
    end
  end

  # PATCH/PUT /dealers/1
  # PATCH/PUT /dealers/1.json
  def update
    respond_to do |format|
      if @dealer.update(dealer_params)
        format.html { redirect_to @dealer, notice: 'Dealer was successfully updated.' }
        format.json { render :show, status: :ok, location: @dealer }
      else
        format.html { render :edit }
        format.json { render json: @dealer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dealers/1
  # DELETE /dealers/1.json
  def destroy
    @dealer.destroy
    respond_to do |format|
      format.html { redirect_to dealers_url, notice: 'Dealer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dealer
      @dealer = Dealer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dealer_params
      params.require(:dealer).permit(:email, :password)
    end
end

app/helpers/dealers_helper.rb
module DealersHelper
end

app/views/dealers/_form.html.erb
<div class="container" style="margin-top: 130px;">
<%= form_with(model: dealer, local: true) do |form| %>
  <% if dealer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dealer.errors.count, "error") %> prohibited this dealer from being saved:</h2>

      <ul>
        <% dealer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/dealers/edit.html.erb
<div class="container" style="margin-top: 130px;">
<h1>Editing Dealer</h1>

<%= render 'form', dealer: @dealer %>

<%= link_to 'Show', @dealer %> |
<%= link_to 'Back', dealers_path %>
</div>

app/views/dealers/index.html.erb
<div class="container" style="margin-top: 130px;">
<p id="notice"><%= notice %></p>

<h1>Dealers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rating</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dealers.each do |dealer| %>
      <tr>
        <td><%= dealer.dealerpersonalinfo.try(:shopname) %></td>
        <td><%= dealer.dealerpersonalinfo.try(:rating) %></td>
        <td><%= dealer.dealerpersonalinfo.try(:phone) %></td>
        <td><%= dealer.try(:email) %></td>
        <%= link_to 'Show', dealer_products_path(dealer) %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dealer', new_dealer_path %>
</div>

app/views/dealers/new.html.erb
<div class="container" style="margin-top: 130px;">
<h1>New Dealer</h1>

<%= render 'form', dealer: @dealer %>

<%= link_to 'Back', dealers_path %>
</div>

app/views/dealers/show.html.erb
<div class="container" style="margin-top: 130px;">
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @dealer.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @dealer.password %>
</p>

<%= link_to 'Edit', edit_dealer_path(@dealer) %> |
<%= link_to 'Back', dealers_path %>
</div>