config/routes.rb
Rails.application.routes.draw do
  get 'delboysession/new'
  post 'delboysession/create'
  delete 'delboysession/destroy'
  get '/delboyconfdel' => 'misc#delboyconfdel', :as => 'conf_del_delboy'
  post '/cartminuss/:id' => 'cart#cartminus', :as => 'crtminus'
  # get 'delaerdelivery/index'
  # get 'delaerdelivery/:id', to: 'delaerdelivery#show'
  get '/homepage' => 'homepage#index', :as => 'home_page'
  # get 'dealersession/new'
  # get 'dealersession/create'
  # get 'dealersession/destroy'
  # get 'customersession/new'
  # post 'customersession/create'
  # delete 'customersession/destroy'
  	resources :dealersession, only: [:new, :create, :destroy]
  	resources :customersession, only: [:new, :create, :destroy]
	resources :customers
	resources :customerpersonalinfos, only: [:new, :create, :edit, :update, :destroy, :show]
	resources :dealers
	resources :dealerpersonalinfos
	resources :products
	resources :cart
	resources :checkout, only: [:index, :create]
	delete '/cancelorder/:conf' => 'checkout#destroy', :as => 'cancel_order'
	resources :delaerdelivery
	get '/confdel' => 'delaerdelivery#conf', :as => 'conf_del'
	get '/search' => 'pages#search', :as => 'search_page'
	get '/pendingorders' => 'misc#pendingorder_user', :as => 'pending_order_user'
	get '/pendingordersbc/:configkey' => 'misc#pendingorder_userbc', :as => 'pending_order_userbc'
	get '/allorders' => 'misc#allorder_user', :as => 'all_order_user'
	get '/delboypendingorders' => 'misc#delboypendings', :as => 'delboy_pendings'
	get '/delboypeningorders/:id' => 'misc#delboypendingsbc', :as => 'delboy_pendingsbc'
	get '/home' => 'homepage#indexws', :as => 'homepagews'
	get '/editaddressform' => 'misc#editaddress_form', :as => 'editadd'
	post '/updateaddress' => 'misc#editaddress', :as => 'editaddpost' 
	post '/checkaval' => 'homepage#checkaval', :as => 'check_servicable'

	root to: "homepage#index"

	get "/login" => "customersession#new", as: "login"
	delete "/logout" => "customersession#destroy", as: "logout"
	get "/dealerlogin" => "dealersession#new", as: "dealerlogin"
	delete "/dealerlogout" => "dealersession#destroy", as: "dealerlogout"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/allorder.rb
class Allorder < ApplicationRecord
  belongs_to :product
  belongs_to :customer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :customer
  belongs_to :product
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_secure_password

	has_one :customerpersonalinfo, dependent: :destroy
	has_many :cart, dependent: :destroy
	has_many :checkout, dependent: :destroy
	validates :email, presence: true
	validates :password, presence: true
end

app/models/customerpersonalinfo.rb
class Customerpersonalinfo < ApplicationRecord
  belongs_to :customer
	validates :name, presence: true
	validates :phone, presence: true
	validates :address, presence: true
end

app/models/dealer.rb
class Dealer < ApplicationRecord
	has_secure_password

	has_one :dealerpersonalinfo
	has_many :products
	validates :email, presence: true
	validates :password, presence: true
	has_many :ptd, through: :products, source: :pendingorder 
end

app/models/dealerpersonalinfo.rb
class Dealerpersonalinfo < ApplicationRecord
  belongs_to :dealer
	validates :shopname, presence: true
	validates :phone, presence: true
end

app/models/delboy.rb
class Delboy < ApplicationRecord
	has_secure_password

	
end

app/models/pendingorder.rb
class Pendingorder < ApplicationRecord
  belongs_to :product
  belongs_to :customer
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :dealer
  has_many :cart, dependent: :destroy
  has_many :pendingorder, dependent: :destroy

  mount_uploader :image, PhotoUploader
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
	skip_before_action :ensure_login_dealer
	skip_before_action :ensure_login_delboy
	def index
		@price = 0
		@cart = current_user().cart
	end


	def update
		@product = Product.find_by(id: params[:id])
		@carttosave = Cart.new
		@carttosave.product_id = @product.id
		if current_user.cart.find_by(product_id: @carttosave.product_id) != nil
			current_user.cart.find_by(product_id: @carttosave.product_id).update!(:quantity => current_user.cart.find_by(product_id: @carttosave.product_id).quantity+1)
		else
			@carttosave.customer_id = current_user.id
			# @carttosave.product_id = @product.id
			@carttosave.quantity = 1
			@carttosave.save
		end
		respond_to do |format|
			format.js
		end
	end

	def cartminus
		@productquan
		@product = Product.find(params[:id])
		@carttodel = Cart.find_by(product_id: @product.id)
		if current_user.cart.find_by(product_id: @carttodel.product_id).quantity == 1
			@carttodel.destroy
			@productquan = 0
		elsif current_user.cart.find_by(product_id: @carttodel.product_id).quantity == nil
			# do nothing
		else
			current_user.cart.find_by(product_id: @carttodel.product_id).update!(:quantity => current_user.cart.find_by(product_id: @carttodel.product_id).quantity-1)
			@productquan = current_user.cart.find_by(product_id: params[:id]).quantity
		end
		respond_to do |format|
			format.js
		end
	end
end

app/controllers/misc_controller.rb
class MiscController < ApplicationController
	skip_before_action :ensure_login_dealer, only: [:pendingorder_user, :allorder_user, :delboypendings, :delboypendingsbc, :delboyconfdel, :pendingorder_userbc, :editaddress, :editaddress_form]
	skip_before_action :ensure_login_delboy, only: [:pendingorder_user, :allorder_user, :pendingorder_userbc, :editaddress, :editaddress_form]

	skip_before_action :ensure_login_user, only: [:delboypendings, :delboypendingsbc, :delboyconfdel]
	
	def pendingorder_user
		@allpo = Pendingorder.where(customer_id: current_user.id).group(:confkey).count
	end

	def pendingorder_userbc
		@key = params[:configkey]
		@pendingsbc = Pendingorder.where(customer_id: current_user.id).where(confkey: @key)
	end
	
	def allorder_user
		@allo = Allorder.where(customer_id: current_user.id).group(:created_at).count
	end

	def delboypendings
		@allptd = Pendingorder.group(:customer_id).count
	end

	def delboypendingsbc
		@customer = params[:id]
		@price = 0
		@allptdbc = Pendingorder.where(customer_id: @customer)
	end

	def delboyconfdel
		@conf = params[:conf_key]
		@todesandadd = Pendingorder.where(confkey: @conf)
		@todesandadd.each do |toaddanddes|
  			@toaddo = Allorder.new
  			@toaddo.quantity = toaddanddes.quantity
  			@toaddo.product_id = toaddanddes.product_id
  			@toaddo.customer_id = toaddanddes.customer_id
  			@toaddo.save
  			# @toaddanddes.destroy
  		end
  		@todesandadd.destroy_all
  		flash['Notification'] = 'Delivered'
  		redirect_to delboy_pendings_path
	end

	def editaddress_form 

	end

	def editaddress 
		current_user.customerpersonalinfo.update!(:name => params[:name])
		current_user.customerpersonalinfo.update!(:phone => params[:phone])
		current_user.customerpersonalinfo.update!(:address => params[:address])
		flash['Notification'] = 'Personal Info updated'
		redirect_to home_page_path
	end

	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dealers_helper.rb
module DealersHelper
end

app/helpers/dealersession_helper.rb
module DealersessionHelper
end

app/helpers/delboysession_helper.rb
module DelboysessionHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/misc_helper.rb
module MiscHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/misc/allorder_user.html.erb
<div class="container" style="margin-top: 130px;">
<h4 class="heading">Your Orders</h4>
<hr>
<% if @allo.count > 0 %>
	<% @allo.each do |key, value| %>
	<hr>
		<b>Ordered on: <%= key %></b>
		<hr>
		<% @ordersbydate = Allorder.where(created_at: key) %>
		<% @ordersbydate.each do |productordered| %>
			<div class="float-left" style="width: 20px; height: 20px;">
				<%= image_tag(productordered.product.image.tiny.url) %>
			</div>
			<div class="float-left" style="margin-left: 8px;">	
				<%= productordered.product.name %>
				(x<%= productordered.quantity %>)
			</div>
			<br>
		<% end %>
	<% end %>
<% else %>
	<div style="width: 100%; margin: 5rem auto 0; text-align: center;">
		<%= image_tag('no-pending.png', size: 150) %>
		<h4><b>BOO!</b></h4>
		<h5><b>Nothing here, but me</b></h5>
		<h6>You haven't placed any Orders.</h6>
	</div>
<% end %>
</div>

app/views/misc/delboypendings.html.erb
<div class="container" style="margin-top: 130px;">
<h1>Products pending to be deliver</h1>
<div>
	<% @allptd.each do |key, value| %>
		To: <%= Customer.find(key).customerpersonalinfo.name %><br/>
		Add: <%= Customer.find(key).customerpersonalinfo.address %><br/>
		Phone: <%= Customer.find(key).customerpersonalinfo.phone %><br/>
		TP: <%= value %>
		<%= link_to 'show', delboy_pendingsbc_path(key)%>
		<br/>
		<br/>
	<% end %>
</div>
</div>

app/views/misc/delboypendingsbc.html.erb
<div class="container" style="margin-top: 130px;">
<h1>Pending Delivery for <%= Customer.find_by(id: @customer).customerpersonalinfo.name %></h1>
<div>
	Enter Conf. Key got from user:
	<%= form_tag(conf_del_delboy_path, :method => "get",   
    class: 'form-inline my-2 my-lg-0') do %>  
  		<div class="input-group">  
    		<%= text_field_tag :conf_key, params[:conf_key], placeholder: "Conformation Key", class: "form-control mr-sm-2" %> 
    		<div class="input-group-btn">  
      			<%= button_tag "Submit", :class => 'btn btn-info',:name => nil%>  
    		</div>  
  		</div>  
	<% end %>
</div>
<div>
	<% @allptdbc.each do |ptdbc| %>
		Product: <%= Product.find(ptdbc.product_id).name %><br/>
		Qty: <%= ptdbc.quantity %><br/>
		Price: <%= Product.find(ptdbc.product_id).price*ptdbc.quantity %>
		<% @price = @price + Product.find(ptdbc.product_id).price*ptdbc.quantity %>
		<hr/>
<% end %>
<div style="height: 200px;"></div>
<div>
	Total : <%= @price %>
</div>
</div>
</div>

app/views/misc/editaddress_form.html.erb
<div class="container" style="margin-top: 130px;">
<div style="width: 100%; margin: 7rem auto 0;">
  <%= form_for(:customerpersonalinfo, url: editaddpost_path, class: 'form-inline my-2 my-lg-0', style: 'text-align: center;') do |form| %>

    <div style="text-align: center; width: 100%;">
      <%= search_field_tag :name, params[:name], placeholder: "Name", class: "form-control mr-sm-2" %><br/>
      <div style="height: 5px;"></div>
      <%= search_field_tag :phone, params[:phone], placeholder: "Phone", class: "form-control mr-sm-2" %><br/>
      <div style="height: 5px;"></div>
      <%= search_field_tag :address, params[:address], placeholder: "Address", class: "form-control mr-sm-2" %><br/>
      <div style="height: 5px;"></div>
      <div class="input-group-btn">  
        <%= button_tag "Submit", :class => 'btn btn-info',:name => nil%>  
      </div>  
    </div>  

  <% end %>
</div>
</div>

app/views/misc/pendingorder_user.html.erb
<div class="container" style="margin-top: 130px;">
<% if @allpo.count > 0 %>	
	<h5 class="heading">Pending Transactions</h5><hr>
	<% @allpo.each do |key, value| %>
		<div class="pendings-productbox">
			<div class="pendings-absolute pendings-timeago"><span class="fa fa-clock" style="margin-right: 4px;"></span><%= time_ago_in_words(Pendingorder.find_by(confkey: key).created_at) %> ago</div>
			<br>
			<div class="divkeyshow pendings-confkey" onclick="showconfkey();"><span class="fa fa-key" style="margin-right: 4px;"></span>********</div>
			<div class="divkeyhide pendings-confkey" onclick="hideconfkey();"><span class="fa fa-lock" style="margin-right: 4px;"></span><%= key %></div>
			<div class="pendings-absolute pendings-totalproducts"><span class="fa fa-hand-holding-box"></span>Total <%= value %> Products</div>
			<br>
			<div class="pentrans-btn btn btn-primary float-left">
				<span class="fa fa-info-circle"></span>
				<%= link_to 'Show Details', pending_order_userbc_path(key), :class => 'font-white' %>
			</div>
			<% if ((Time.now - Pendingorder.find_by(confkey: key).created_at)/60) < 30 %>
				<div class="pentrans-btn btn btn-danger float-left">	
					<span class="fa fa-trash-alt"></span>
					<%= link_to 'Cancel Order', cancel_order_path(key), :class => 'font-white', method: :delete, data: { confirm: 'Are you sure to cancel your order? :(' } %>
				</div>
			<% end %>
			<br>
			<br>
			<hr>
		</div>
	<% end %>
	<a href="https://wa.me/919057686840/">
		<div class="whatsapp-help font-white"> 
			<%= image_tag('whatsapp-icon.png', size: 40, :class => 'whatsapp-icon-class') %>
			<span class="whatsapp-icon-class">Need <br> help?</span>
		</div>
	</a>
<% else %>
	<div style="width: 100%; margin: 7rem auto 0; text-align: center;">
		<%= image_tag('no-pending.png', size: 150) %>
		<h4><b>BOO!</b></h4>
		<h5><b>Nothing here, but me</b></h5>
		<h6>You don't have any pending transactions.</h6>
	</div>
<% end %>

<script type="text/javascript">
	$(function() {
		$('.divkeyhide').css('display','none');
	})
	function showconfkey() {
		$('.divkeyhide').css('display','block');
		$('.divkeyshow').css('display','none');
	}
	function hideconfkey() {
		$('.divkeyhide').css('display','none');
		$('.divkeyshow').css('display','block');
	}
</script>
</div>

app/views/misc/pendingorder_userbc.html.erb
<div class="container" style="margin-top: 130px;">
Conf. Key => <%= @key %>
<br>
<% @pendingsbc.each do |products| %>
	<br>
	<div class="float-left" style="width: 20px; height: 20px;">
		<%= image_tag(products.product.image.tiny.url) %>
	</div>
	<div class="float-left" style="margin-left: 8px;">
		<%= products.product.name %>
		(x<%= products.quantity %>)
	</div>
	<%  %>
<% end %>
</div>