config/routes.rb
Rails.application.routes.draw do
  get 'delboysession/new'
  post 'delboysession/create'
  delete 'delboysession/destroy'
  get '/delboyconfdel' => 'misc#delboyconfdel', :as => 'conf_del_delboy'
  post '/cartminuss/:id' => 'cart#cartminus', :as => 'crtminus'
  # get 'delaerdelivery/index'
  # get 'delaerdelivery/:id', to: 'delaerdelivery#show'
  get '/homepage' => 'homepage#index', :as => 'home_page'
  # get 'dealersession/new'
  # get 'dealersession/create'
  # get 'dealersession/destroy'
  # get 'customersession/new'
  # post 'customersession/create'
  # delete 'customersession/destroy'
  	resources :dealersession, only: [:new, :create, :destroy]
  	resources :customersession, only: [:new, :create, :destroy]
	resources :customers
	resources :customerpersonalinfos, only: [:new, :create, :edit, :update, :destroy, :show]
	resources :dealers
	resources :dealerpersonalinfos
	resources :products
	resources :cart
	resources :checkout, only: [:index, :create]
	delete '/cancelorder/:conf' => 'checkout#destroy', :as => 'cancel_order'
	resources :delaerdelivery
	get '/confdel' => 'delaerdelivery#conf', :as => 'conf_del'
	get '/search' => 'pages#search', :as => 'search_page'
	get '/pendingorders' => 'misc#pendingorder_user', :as => 'pending_order_user'
	get '/pendingordersbc/:configkey' => 'misc#pendingorder_userbc', :as => 'pending_order_userbc'
	get '/allorders' => 'misc#allorder_user', :as => 'all_order_user'
	get '/delboypendingorders' => 'misc#delboypendings', :as => 'delboy_pendings'
	get '/delboypeningorders/:id' => 'misc#delboypendingsbc', :as => 'delboy_pendingsbc'
	get '/home' => 'homepage#indexws', :as => 'homepagews'
	get '/editaddressform' => 'misc#editaddress_form', :as => 'editadd'
	post '/updateaddress' => 'misc#editaddress', :as => 'editaddpost' 
	post '/checkaval' => 'homepage#checkaval', :as => 'check_servicable'

	root to: "homepage#index"

	get "/login" => "customersession#new", as: "login"
	delete "/logout" => "customersession#destroy", as: "logout"
	get "/dealerlogin" => "dealersession#new", as: "dealerlogin"
	delete "/dealerlogout" => "dealersession#destroy", as: "dealerlogout"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customerpersonalinfo.rb
class Customerpersonalinfo < ApplicationRecord
  belongs_to :customer
	validates :name, presence: true
	validates :phone, presence: true
	validates :address, presence: true
end

app/controllers/customerpersonalinfos_controller.rb
class CustomerpersonalinfosController < ApplicationController
  before_action :set_customerpersonalinfo, only: [:show, :edit, :update, :destroy]
  # skip_before_action :ensure_login, only: [:new, :create]
  skip_before_action :ensure_login_dealer
  
  skip_before_action :ensure_login_delboy

  # GET /customerpersonalinfos
  # GET /customerpersonalinfos.json
  def index
    @customerpersonalinfos = current_user().customerpersonalinfo
  end

  # GET /customerpersonalinfos/1
  # GET /customerpersonalinfos/1.json
  def show
  end

  # GET /customerpersonalinfos/new
  def new
    @customerpersonalinfo = current_user().build_customerpersonalinfo
  end

  # GET /customerpersonalinfos/1/edit
  def edit
  end

  # POST /customerpersonalinfos
  # POST /customerpersonalinfos.json
  def create
    @customerpersonalinfo = current_user().build_customerpersonalinfo(customerpersonalinfo_params)

    respond_to do |format|
      if @customerpersonalinfo.save
        format.html { redirect_to root_path, notice: 'Customerpersonalinfo was successfully created.' }
        format.json { render :show, status: :created, location: @customerpersonalinfo }
      else
        format.html { render :new }
        format.json { render json: @customerpersonalinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customerpersonalinfos/1
  # PATCH/PUT /customerpersonalinfos/1.json
  def update
    respond_to do |format|
      if @customerpersonalinfo.update(customerpersonalinfo_params)
        format.html { redirect_to root_path, notice: 'Customerpersonalinfo was successfully updated.' }
        format.json { render :show, status: :ok, location: @customerpersonalinfo }
      else
        format.html { render :edit }
        format.json { render json: @customerpersonalinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customerpersonalinfos/1
  # DELETE /customerpersonalinfos/1.json
  def destroy
    @customerpersonalinfo.destroy
    respond_to do |format|
      format.html { redirect_to customerpersonalinfos_url, notice: 'Customerpersonalinfo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customerpersonalinfo
      @customerpersonalinfo = current_user.customerpersonalinfo
    end

    # Only allow a list of trusted parameters through.
    def customerpersonalinfo_params
      params.permit(:name, :phone, :address, :pincode)
    end
end

app/helpers/customerpersonalinfos_helper.rb
module CustomerpersonalinfosHelper
end

app/views/customerpersonalinfos/_form.html.erb
<div class="container" style="margin-top: 130px;">
<div style="width: 100%; margin: 7rem auto 0;">
  <%= form_with(model: customerpersonalinfo, local: true, class: 'form-inline my-2 my-lg-0', style: 'text-align: center;') do |form| %>
    <% if customerpersonalinfo.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(customerpersonalinfo.errors.count, "error") %> prohibited this customerpersonalinfo from being saved:</h2>

        <ul>
          <% customerpersonalinfo.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    

    <div style="text-align: center; width: 100%;">
      <%= search_field_tag :name, params[:name], placeholder: "Name", class: "form-control mr-sm-2" %><br/>
      <div style="height: 5px;"></div>
      <%= search_field_tag :phone, params[:phone], placeholder: "Phone", class: "form-control mr-sm-2" %><br/>
      <div style="height: 5px;"></div>
      <%= search_field_tag :address, params[:address], placeholder: "Address", class: "form-control mr-sm-2" %><br/>
      <div style="height: 5px;"></div>
      <%= phone_field_tag :pincode, params[:pincode], placeholder: "Pincode", class: "form-control mr-sm-2" %><br/>
      <div style="height: 5px;"></div>
      <div class="input-group-btn">  
        <%= button_tag "Submit", :class => 'btn btn-info',:name => nil%>  
      </div>  
    </div>  

  <% end %>
</div>
</div>

app/views/customerpersonalinfos/edit.html.erb
<div class="container" style="margin-top: 130px;">
<h1>Editing Customerpersonalinfo</h1>

<%= render 'form', customerpersonalinfo: @customerpersonalinfo %>

<%= link_to 'Show', @customerpersonalinfo %> |
<%= link_to 'Back', customerpersonalinfos_path %>
</div>

app/views/customerpersonalinfos/index.html.erb
<div class="container" style="margin-top: 130px;">
<h1>Customerpersonalinfos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @customerpersonalinfos.name %></td>
        <td><%= @customerpersonalinfos.phone %></td>
        <td><%= @customerpersonalinfos.address %></td>
        <td><%= link_to 'Show', customerpersonalinfo_path %></td>
        <td><%= link_to 'Edit', edit_customerpersonalinfo_path(customerpersonalinfo) %></td>
        <td><%= link_to 'Destroy', customerpersonalinfo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  </tbody>
</table>

<br>

<%= link_to 'New Customerpersonalinfo', new_customerpersonalinfo_path %>
</div>

app/views/customerpersonalinfos/new.html.erb
<div class="container" style="margin-top: 130px;">
<h1>Fill in your details</h1>

<%= render 'form', customerpersonalinfo: @customerpersonalinfo %>
</div>

app/views/customerpersonalinfos/show.html.erb
<div class="container" style="margin-top: 130px;">
<p>
  <strong>Name:</strong>
  <%= @customerpersonalinfo.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customerpersonalinfo.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @customerpersonalinfo.address %>
</p>

<%= link_to 'Edit', edit_customerpersonalinfo_path(@customerpersonalinfo) %> |
<%= link_to 'Back', customerpersonalinfos_path %>
</div>